### ISSUE TITLE
Error installing on Magento v2.4.2 using PHP 7.4

### ISSUE THREAD

**Issue by craigfleming** [markshust/magento2-module-extrabodyclasses#2]
I can't install this extension on a PHP 7.4 and Magento v2.4.2 system.

I used `composer require markshust/magento2-module-extrabodyclasses` to add to composer.json and received the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for markshust/magento2-module-extrabodyclasses ^1.0 -> satisfiable by markshust/magento2-module-extrabodyclasses[1.0.0, 1.0.1, 1.0.2].
    - Can only install one of: magento/framework[103.0.2, 102.0.7].
    - Can only install one of: magento/framework[102.0.7, 103.0.2].
    - Can only install one of: magento/framework[102.0.7, 103.0.2].
    - Conclusion: install magento/framework 102.0.7
    - Installation request for magento/framework (locked at 103.0.2) -> satisfiable by magento/framework[103.0.2].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by craigfleming** [comment]
@markshust - Looks like the latest pull request is what has caused this issue - https://github.com/markshust/magento2-module-extrabodyclasses/pull/1

Can you please investigate?

**Comment by markshust** [comment]
@craigfleming sorry for the belated reply, I've been out of town for more than a week. I updated the `magento/framework` dependency to be compatible with `103`, and tagged version `1.0.3`. Can you see if this version works for you?

**Comment by craigfleming** [comment]
@markshust - Works great now. Thanks for sorting this out.
